In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_daf9d661a11646e79c460229f7d3d7c1 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='H7ytk8OiWnyxMwbKJjzapPavnwOn9TB7eHSaOMktoQLp',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_daf9d661a11646e79c460229f7d3d7c1.get_object(Bucket='3dprinting-donotdelete-pr-pzmhxfhooskuap',Key='printing.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head()



layer_height  wall_thickness  infill_density infill_pattern  \
0          0.02               8              90           grid   
1          0.02               7              90      honeycomb   
2          0.02               1              80           grid   
3          0.02               4              70      honeycomb   
4          0.02               6              90           grid   

   nozzle_temperature  bed_temperature  print_speed  fan_speed  roughness  \
0                 220               60           40          0         25   
1                 225               65           40         25         32   
2                 230               70           40         50         40   
3                 240               75           40         75         68   
4                 250               80           40        100         92   

   tension_strenght  elongation material  
0                18         1.2      abs  
1                16         1.4      abs  
2                 8         0.8      abs  
3                10         0.5      abs  
4                 5         0.7      abs

In [3]:
df

layer_height  wall_thickness  infill_density infill_pattern  \
0           0.02               8              90           grid   
1           0.02               7              90      honeycomb   
2           0.02               1              80           grid   
3           0.02               4              70      honeycomb   
4           0.02               6              90           grid   
5           0.02              10              40      honeycomb   
6           0.02               5              10           grid   
7           0.02              10              10      honeycomb   
8           0.02               9              70           grid   
9           0.02               8              40      honeycomb   
10          0.06               6              80           grid   
11          0.06               2              20      honeycomb   
12          0.06              10              50           grid   
13          0.06               6              10      honeycomb   
14          0.06               3              50           grid   
15          0.06              10              90      honeycomb   
16          0.06               3              40           grid   
17          0.06               8              30      honeycomb   
18          0.06               5              80           grid   
19          0.06              10              50      honeycomb   
20          0.10               1              40           grid   
21          0.10               2              30      honeycomb   
22          0.10               1              50           grid   
23          0.10               9              80      honeycomb   
24          0.10               2              60           grid   
25          0.10               1              50      honeycomb   
26          0.10               4              40           grid   
27          0.10               3              50      honeycomb   
28          0.10               4              90           grid   
29          0.10               1              30      honeycomb   
30          0.15               4              50           grid   
31          0.15               7              10      honeycomb   
32          0.15               6              50           grid   
33          0.15               1              50      honeycomb   
34          0.15               7              80           grid   
35          0.15               3              80      honeycomb   
36          0.15               4              50           grid   
37          0.15              10              30      honeycomb   
38          0.15               6              40           grid   
39          0.15               1              10      honeycomb   
40          0.20               4              80           grid   
41          0.20               9              90      honeycomb   
42          0.20               7              30           grid   
43          0.20               6              90      honeycomb   
44          0.20               3              80           grid   
45          0.20               5              60      honeycomb   
46          0.20               4              20           grid   
47          0.20               5              60      honeycomb   
48          0.20               7              40           grid   
49          0.20               3              60      honeycomb   

    nozzle_temperature  bed_temperature  print_speed  fan_speed  roughness  \
0                  220               60           40          0         25   
1                  225               65           40         25         32   
2                  230               70           40         50         40   
3                  240               75           40         75         68   
4                  250               80           40        100         92   
5                  200               60           40          0         60   
6                  205               65 

In [4]:
df.isnull().any()

layer_height          False
wall_thickness        False
infill_density        False
infill_pattern        False
nozzle_temperature    False
bed_temperature       False
print_speed           False
fan_speed             False
roughness             False
tension_strenght      False
elongation            False
material              False
dtype: bool

In [5]:
x=df.iloc[:,0:11].values


In [6]:
y=df.iloc[:,11].values

In [7]:
x

array([[0.02, 8, 90, 'grid', 220, 60, 40, 0, 25, 18, 1.2],
       [0.02, 7, 90, 'honeycomb', 225, 65, 40, 25, 32, 16, 1.4],
       [0.02, 1, 80, 'grid', 230, 70, 40, 50, 40, 8, 0.8],
       [0.02, 4, 70, 'honeycomb', 240, 75, 40, 75, 68, 10, 0.5],
       [0.02, 6, 90, 'grid', 250, 80, 40, 100, 92, 5, 0.7],
       [0.02, 10, 40, 'honeycomb', 200, 60, 40, 0, 60, 24, 1.1],
       [0.02, 5, 10, 'grid', 205, 65, 40, 25, 55, 12, 1.3],
       [0.02, 10, 10, 'honeycomb', 210, 70, 40, 50, 21, 14, 1.5],
       [0.02, 9, 70, 'grid', 215, 75, 40, 75, 24, 27, 1.4],
       [0.02, 8, 40, 'honeycomb', 220, 80, 40, 100, 30, 25, 1.7],
       [0.06, 6, 80, 'grid', 220, 60, 60, 0, 75, 37, 2.4],
       [0.06, 2, 20, 'honeycomb', 225, 65, 60, 25, 92, 12, 1.4],
       [0.06, 10, 50, 'grid', 230, 70, 60, 50, 118, 16, 1.3],
       [0.06, 6, 10, 'honeycomb', 240, 75, 60, 75, 200, 9, 0.8],
       [0.06, 3, 50, 'grid', 250, 80, 60, 100, 220, 10, 1.0],
       [0.06, 10, 90, 'honeycomb', 200, 60, 60, 0, 126, 27, 2.

In [8]:
y

array(['abs', 'abs', 'abs', 'abs', 'abs', 'pla', 'pla', 'pla', 'pla',
       'pla', 'abs', 'abs', 'abs', 'abs', 'abs', 'pla', 'pla', 'pla',
       'pla', 'pla', 'abs', 'abs', 'abs', 'abs', 'abs', 'pla', 'pla',
       'pla', 'pla', 'pla', 'abs', 'abs', 'abs', 'abs', 'abs', 'pla',
       'pla', 'pla', 'pla', 'pla', 'abs', 'abs', 'abs', 'abs', 'abs',
       'pla', 'pla', 'pla', 'pla', 'pla'], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
lr=LabelEncoder()

In [10]:
x[:,3]=lr.fit_transform(x[:,3])

In [11]:
x[:,3]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1], dtype=object)

In [12]:
x

array([[0.02, 8, 90, 0, 220, 60, 40, 0, 25, 18, 1.2],
       [0.02, 7, 90, 1, 225, 65, 40, 25, 32, 16, 1.4],
       [0.02, 1, 80, 0, 230, 70, 40, 50, 40, 8, 0.8],
       [0.02, 4, 70, 1, 240, 75, 40, 75, 68, 10, 0.5],
       [0.02, 6, 90, 0, 250, 80, 40, 100, 92, 5, 0.7],
       [0.02, 10, 40, 1, 200, 60, 40, 0, 60, 24, 1.1],
       [0.02, 5, 10, 0, 205, 65, 40, 25, 55, 12, 1.3],
       [0.02, 10, 10, 1, 210, 70, 40, 50, 21, 14, 1.5],
       [0.02, 9, 70, 0, 215, 75, 40, 75, 24, 27, 1.4],
       [0.02, 8, 40, 1, 220, 80, 40, 100, 30, 25, 1.7],
       [0.06, 6, 80, 0, 220, 60, 60, 0, 75, 37, 2.4],
       [0.06, 2, 20, 1, 225, 65, 60, 25, 92, 12, 1.4],
       [0.06, 10, 50, 0, 230, 70, 60, 50, 118, 16, 1.3],
       [0.06, 6, 10, 1, 240, 75, 60, 75, 200, 9, 0.8],
       [0.06, 3, 50, 0, 250, 80, 60, 100, 220, 10, 1.0],
       [0.06, 10, 90, 1, 200, 60, 60, 0, 126, 27, 2.2],
       [0.06, 3, 40, 0, 205, 65, 60, 25, 145, 23, 1.9],
       [0.06, 8, 30, 1, 210, 70, 60, 50, 88, 26, 1.6],
     

In [13]:
y

array(['abs', 'abs', 'abs', 'abs', 'abs', 'pla', 'pla', 'pla', 'pla',
       'pla', 'abs', 'abs', 'abs', 'abs', 'abs', 'pla', 'pla', 'pla',
       'pla', 'pla', 'abs', 'abs', 'abs', 'abs', 'abs', 'pla', 'pla',
       'pla', 'pla', 'pla', 'abs', 'abs', 'abs', 'abs', 'abs', 'pla',
       'pla', 'pla', 'pla', 'pla', 'abs', 'abs', 'abs', 'abs', 'abs',
       'pla', 'pla', 'pla', 'pla', 'pla'], dtype=object)

In [14]:
lr1=LabelEncoder()

In [15]:
y=lr1.fit_transform(y)

In [16]:
y


array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1])

In [17]:
x[11,:]

array([0.06, 2, 20, 1, 225, 65, 60, 25, 92, 12, 1.4], dtype=object)

In [18]:
y[11]

0

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

In [21]:
pipeline = Pipeline([('scaler', StandardScaler()),('classifier',DecisionTreeClassifier())])
pipeline.fit(x_train, y_train)
predictions = pipeline.predict(x_test)

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [22]:
predictions

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0])

In [23]:
pipeline.predict([[0.02, 10, 40, 1, 200, 60, 40, 0, 60, 24, 1.1]])

array([1])

In [24]:
import pickle
pickle.dump(pipeline,open("project.pkl",'wb'))

In [25]:
!mkdir model-dir
!cp project.pkl model-dir

In [26]:
!tar -zcvf project.tar.gz project.pkl

project.pkl
